//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS_Summer_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int ApprovedID { get; set; }
        public string PendingApprovalID { get; set; }
        public string DisapprovedID { get; set; }
        public string InactiveID { get; set; }
        public string AllID { get; set; }
    
        public virtual VolunteerInfo VolunteerInfo { get; set; }
    }
}
