//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cocktail_Bar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int OrderID { get; set; }
        public string CocktailID { get; set; }
    
        public virtual Cocktails Entity1 { get; set; }
    }
}
